[package]
name = "rediSQL"
version = "0.3.0"
authors = ["Simone Mosciatti <simone@redbeardlab.tech>"]
build = "build.rs"

[lib]
name = "redis_sql"
crate-type = ["cdylib"]

[build-dependencies]
bindgen = "0.30.0"
cc = {version = "1.0.3", features = ["parallel"]}

[dependencies]
libc = "0.2.21"
fnv = "1.0.5"
uuid = { version = "0.4", features = ["v4"] }
log = "0.3.8"
env_logger = "0.4.3"

[features]
default = ["community"]

pro = []
community = []
